### ISSUE TITLE
이슈 핸들링에서 사용되는 enum 데이터에 대한 문의

### ISSUE THREAD

**Issue by DongGeon0908** [depromeet/pingpong-be#33]
https://github.com/depromeet/pingpong-be/blob/a356e0e5c21406dd81eda377dbc63d44f0bda526/winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/enums/ErrorMessage.java#L12

안녕하세요! 염탐하다가 궁금한게 있어 문의드려요
위에 링크를 걸어두긴 했는데요. enum부분에서 statusCode를 한번더 까는 이유가 있을까요? 그대로 가지고 있는게 확장하는데 더 편하지 않을까 생각되어서요

**Comment by minsoozz** [comment]
클라이언트에 응답 시 오류코드와, 메시지만 전달해주기로 프로젝트 내부적으로 가이드를 정해서 그에 맞게 구성하였습니다.
말씀하신 것처럼 확장을 고려한다면 `INTERNAL_SERVER_ERROR` 자체를 그대로 가지고 있는 방법도 있을 것 같네요. 감사합니다~

**Comment by minsoozz** [comment]
클라이언트에 응답 시 오류코드와, 메시지만 전달해주기로 프로젝트 가이드를 정해서 그에 맞게 구성하였습니다.
말씀하신 것처럼 확장을 고려한다면 INTERNAL_SERVER_ERROR 자체를 그대로 가지고 있는 방법도 있을 것 같네요. 감사합니다~

**Comment by minsoozz** [comment]
초기 구성 시 확장에 대한 부분은 고려하지 못하고 code 만 반환해주려고 했어요. 지금 다시 한번 생각해보면 동건님 말씀처럼 수정하는 방법이 더 좋아보이네요. 피드백 감사합니다 자주 놀러오세요~👍

**Comment by minsoozz** [comment]
추가적으로 답변드리지면 HttpStatus 로 표현하지 못하는 프로젝트 자체 오류 코드를 구성할 경우 해당 객체를 사용하지 못하기에 enum 의 프로퍼티로 객체를 사용하기보다는 숫자로 표현하였습니다

**Comment by DongGeon0908** [comment]
@minsoozz 답변 감사합니다!!
그렇다면, code는 HttpStatus가 아니라, 특수한 ErrorCode를 의미하는거겠군요!! 

예전에 페이스북, 인스타그램의 api 응답을 조금 찾아본게 있는데요! 도움이 될 것 같아 공유드려요~!

https://yeti.tistory.com/212
